#!/usr/bin/env python3
"""
audit_dashboard.py -- DAILY SELF-AUDIT. Runs right after the daily rebuild (Windows
7:10 AM task + cloud daily.yml). Independently re-aggregates every dashboard metric from
that day's reports and diffs it against the DEPLOYED index.html data blocks. Catches
staleness, a missing/short report, aggregation drift, a tech dropping out, etc.

It reuses the engine's report-SOURCING primitives (which file, which columns, the ESTIMATE
-> Scheduled fallback) so it tracks the current methodology and never false-alarms on a
legit method change -- but it RE-AGGREGATES on its own and compares to what actually
shipped in index.html.

Logs one dated PASS/FAIL line to ropp-audit.log next to this script and prints a summary.
Exit code 1 if any mismatch (so the pipeline can surface it); the rebuild is NOT reverted.

Usage:  py audit_dashboard.py [--index PATH]
"""
import os, sys, json, argparse
from collections import defaultdict
from datetime import date, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import UPDATE_DASHBOARD as U   # reuse report resolution + primitives (NOT the build_* funcs)

ap = argparse.ArgumentParser()
ap.add_argument("--index", default=None, help="path to the deployed index.html")
ap.add_argument("--date", default=None)
A = ap.parse_args()
TODAY = datetime.strptime(A.date, "%Y-%m-%d").date() if A.date else date.today()
YEAR, NM = U.YEAR, TODAY.month
MN = U.MONTH_NAMES

INDEX = A.index or next((p for p in (
    r"C:\Users\johns\sierra-ropp-dashboard\index.html",
    os.path.join(os.getcwd(), "site", "index.html"),
    os.path.join(os.getcwd(), "index.html")) if os.path.exists(p)), None)
if not INDEX or not os.path.exists(INDEX):
    print("AUDIT: could not find index.html"); sys.exit(2)

# ---------- independent re-aggregation (engine primitives, our own tallies) ----------
calls = defaultdict(lambda: [0, 0]); tgls = defaultdict(lambda: [0, 0]); rev = defaultdict(lambda: [0.0, 0.0])
canc = defaultdict(lambda: [0, 0]); sd = defaultdict(lambda: [0, 0, 0])
opp = defaultdict(lambda: [0, 0]); soldc = defaultdict(lambda: [0, 0]); sales = defaultdict(lambda: [0.0, 0.0])

for grp, r in U.iter_grouped(U.load_rows("Revenue_By_JobType.xlsx"), "Assigned Technicians", 3):
    t = U.resolve(r[7]) or U.resolve(grp); d = U.to_date(r[4])
    if t and d and d.year == YEAR:
        calls[t][0] += 1
        if d.month == NM: calls[t][1] += 1

SUB = U.sub_by_srcjob()
for grp, r in U.iter_grouped(U.load_rows("ROPP_TGLs_Created.xlsx"), "Assigned Technicians", 1):
    t = U.resolve(r[3]) or U.resolve(grp); d = U.to_date(r[5])
    if t and d and d.year == YEAR:
        v = SUB.get(U.jobkey(r[1]), 0.0)
        tgls[t][0] += 1; rev[t][0] += v
        if d.month == NM: tgls[t][1] += 1; rev[t][1] += v

for grp, r in U.iter_grouped(U.load_rows("ROPP_Cancelations.xlsx"), "Lead Generated By", 1):
    t = U.resolve(r[10]) or U.resolve(grp); cd = U.to_date(r[9]); sdt = U.to_date(r[7])
    if t and cd and cd.year == YEAR: canc[t][0] += 1
    if t and sdt and sdt.year == YEAR and sdt.month == NM: canc[t][1] += 1

for grp, r in U.iter_grouped(U.load_rows("ROPP_TGLs_Scheduled.xlsx"), "Assigned Technicians", 1):
    t = U.resolve(r[4]); ran = U.to_date(r[6]); cr = U.to_date(r[7])
    if t and ran and ran.year == YEAR:
        sd[t][0] += 1
        if cr and ran == cr: sd[t][1] += 1
        if cr and (ran - cr).days == 1: sd[t][2] += 1

for src, rd, sub in U.tgl_estimates():
    if src and rd and rd.year == YEAR:
        opp[src][0] += 1
        if rd.month == NM: opp[src][1] += 1
        if sub > 0:
            soldc[src][0] += 1; sales[src][0] += sub
            if rd.month == NM: soldc[src][1] += 1; sales[src][1] += sub

# ---------- deployed blocks ----------
html = open(INDEX, encoding="utf-8").read()
def block(name):
    i = html.find("const " + name); j = html.find("{", i); depth = 0; k = j
    while k < len(html):
        if html[k] == '{': depth += 1
        elif html[k] == '}':
            depth -= 1
            if depth == 0: return json.loads(html[j:k+1])
        k += 1
INIT = block("INITIAL_DATA"); CAN = block("CANCEL_DATA"); SAM = block("SAMEDAY_DATA"); CRD = block("CLOSE_RATE_DATA")

diffs = []; nchk = 0
def chk(lbl, exp, got, tol=0):
    global nchk; nchk += 1
    if abs((exp or 0) - (got or 0)) > tol: diffs.append(f"{lbl}: dashboard={got} recount={exp}")

for n, dd in INIT.items():
    for per, i in (("ytd", 0), ("mtd", 1)):
        chk(f"{n}.{per}.calls", calls[n][i], dd[per].get("calls", 0))
        chk(f"{n}.{per}.tgls",  tgls[n][i],  dd[per].get("tgls", 0))
        chk(f"{n}.{per}.revenue", round(rev[n][i]), round(dd[per].get("revenue", 0)), tol=2)
for n, v in CAN.get("ytd", {}).items():
    chk(f"{n}.cancelled", canc[n][0], v.get("cancelled", 0))
for n, v in SAM.get("ytd", {}).items():
    for f, i in (("total", 0), ("flipped", 1), ("nextday", 2)):
        chk(f"{n}.sameday.{f}", sd[n][i], v.get(f, 0))
for grp in ("team_a", "team_b", "combined"):
    for row in CRD.get(grp, []):
        n = row["name"]
        for per, i in (("ytd", 0), ("mtd", 1)):
            g = row.get(per, {})
            chk(f"{grp}/{n}.{per}.ran",   opp[n][i],   g.get("ran", 0))
            chk(f"{grp}/{n}.{per}.sold",  soldc[n][i], g.get("sold", 0))
            chk(f"{grp}/{n}.{per}.sales", round(sales[n][i]), round(g.get("sales", 0)), tol=2)

yc = sum(v[0] for v in calls.values()); yt = sum(v[0] for v in tgls.values()); yr = round(sum(v[0] for v in rev.values()))
status = "PASS" if not diffs else "FAIL"
stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
line = f"{stamp}  AUDIT {status}  {nchk} checks  {len(diffs)} mismatches  |  DEPT YTD {yc}c/{yt}t/${yr:,}"
print("="*70); print(line); print("="*70)
if diffs:
    print("MISMATCHES (dashboard vs independent recount from today's reports):")
    for d in diffs[:40]: print("  " + d)
    if len(diffs) > 40: print(f"  ...and {len(diffs)-40} more")
else:
    print("All dashboard values reconcile to today's reports.")
try:
    with open(os.path.join(HERE, "ropp-audit.log"), "a", encoding="utf-8") as f:
        f.write(line + ("" if not diffs else "  :: " + " ; ".join(diffs[:8])) + "\n")
except Exception:
    pass
sys.exit(0 if not diffs else 1)
