#!/usr/bin/env python3
"""Feed the existing ROPP builder (UPDATE_DASHBOARD.py) from LIVE ServiceTitan data.

Reads the cached API report payloads in cache/*.json (fetched via the Reporting API),
converts each to the exact Excel row shape the builder expects (API field order already
matches the Excel column order — grouped reports just get a leading blank column + tech
group-header rows), monkeypatches U.load_rows, and regenerates the ROPP data blocks.

Run cache_reports() first (separate step) to refresh cache/*.json from the API.
"""
import json, os, re, sys, datetime as dt

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)   # cloud: UPDATE_DASHBOARD / st_client live beside this file (private repo)
CLAUDE = "/Users/johnschwinghamer/Library/CloudStorage/OneDrive-SierraCoolsLV/CLAUDE STUFF"
if os.path.isdir(CLAUDE): sys.path.insert(0, CLAUDE)   # Mac: modules live in CLAUDE STUFF
import UPDATE_DASHBOARD as U   # auto_update_dashboard imported lazily in build_into() to avoid a cycle

ISO = re.compile(r"^\d{4}-\d{2}-\d{2}T")
def _cell(v):
    if isinstance(v, str) and ISO.match(v):
        try: return dt.datetime.fromisoformat(v).replace(tzinfo=None)
        except ValueError: return v
    return v

# canonical builder name -> (cache file, grouped?, group-header prefix, group col in API row)
CONFIG = {
    "ROPP_TGLs_Created.xlsx":  ("tgls_created",  True,  "Assigned Technicians", 2),
    "ROPP_TGLs_Scheduled.xlsx":("scheduled",     True,  "Assigned Technicians", 2),
    "ROPP_Cancelations.xlsx":  ("cancellations", True,  "Lead Generated By",    9),
    "Revenue_By_JobType.xlsx": ("revenue",       True,  "Assigned Technicians", 6),
    "ROPP_Estimate_TGLs.xlsx": ("estimate",      False, None,                   None),
}

def _tgl_jobset():
    """Job#s in the TGLs-Created report — the emailed ESTIMATE keeps only estimates
    whose source lead job is one of these (a real ROPP TGL), not a job-type filter."""
    c = json.load(open(os.path.join(HERE, "cache", "tgls_created.json")))
    j = c["fields"].index("JobNumber")
    return {U.jobkey(r[j]) for r in c["rows"] if U.jobkey(r[j])}
# Excel header labels (row 0) — must carry the substrings the ESTIMATE header-detector needs.
EST_HEADER = ["Job #","Job Type","Assigned Technicians","Lead Generated From Source Technician",
              "Lead Generated From Source Job Number","Scheduled Date","Created Date",
              "Business Unit","Jobs Estimate Sales Subtotal"]

def _convert(canon):
    cache = json.load(open(os.path.join(HERE, "cache", CONFIG[canon][0] + ".json")))
    return _convert_rows(canon, cache["fields"], cache["rows"])

def _convert_rows(canon, fields, rows):
    cfg = CONFIG[canon]
    idx = {f: i for i, f in enumerate(fields)}
    rows = [[_cell(c) for c in r] for r in rows]
    if canon == "ROPP_Estimate_TGLs.xlsx":
        tgl_set = _tgl_jobset(); si = idx["LeadGeneratedFromSourceJobNumber"]
        rows = [r for r in rows if U.jobkey(r[si]) in tgl_set]   # source lead job is a ROPP TGL
        return [EST_HEADER] + rows                            # flat: no leading blank, no groups
    # grouped: header + per-tech group headers + ['']+row
    gcol = cfg[3]; prefix = cfg[2]
    out = [[""] + fields]                                     # row 0 header (skipped by iter_grouped)
    rows.sort(key=lambda r: str(r[gcol] or ""))
    cur = object()
    for r in rows:
        g = r[gcol]
        if g != cur:
            out.append([prefix + ": " + str(g or "")]); cur = g
        out.append([""] + r)
    return out

_CACHE = {}
def load_rows(fname):
    if fname not in _CACHE:
        _CACHE[fname] = _convert(fname)
    return _CACHE[fname]

# DateType per report, calibrated against the emailed Excel row counts (2026-07-10).
FETCH = {"tgls_created":("technician",642925621,3), "cancellations":("technician",642928003,8),
         "scheduled":("technician",660537364,1), "estimate":("technician",648754648,1),
         "revenue":("accounting",379143819,1)}

def _fetch_report(cache_name, frm, to):
    """Live-fetch one report for [frm,to]; returns (fields, rows). Paced, 429 backoff."""
    import st_client as st, urllib.error, time
    cat, rid, dt_ = FETCH[cache_name]
    out = []; page = 1; fields = None
    while True:
        for _ in range(8):
            try:
                r = st.run_report(cat, rid, [{"name":"DateType","value":dt_},
                    {"name":"From","value":frm}, {"name":"To","value":to}], page=page, page_size=5000); break
            except urllib.error.HTTPError as e:
                if e.code == 429: time.sleep(int(e.headers.get("Retry-After","30") or 30) + 1); continue
                raise
        else:
            raise RuntimeError("retries exhausted")
        fields = [f["name"] for f in r["fields"]]; out += r.get("data", [])
        if not r.get("hasMore") or not r.get("data"): break
        page += 1; time.sleep(1)
    return fields, out

def fetch_report_rows(canonical, frm, to):
    """Live-fetch a report for [frm,to] and return Excel-shaped rows (no cache).
    Used by the 15-min Today-tab job to pull today's Revenue/TGLs/Scheduled from the API."""
    return _convert_rows(canonical, *_fetch_report(CONFIG[canonical][0], frm, to))
def cache_reports(frm=None, to=None):
    """Refresh cache/*.json from the live Reporting API (paced, 429-backoff).
    Defaults to YTD-through-today so scheduled daily runs stay current."""
    _t = dt.date.today()
    frm = frm or f"{_t.year}-01-01"
    to = to or _t.isoformat()
    import st_client as st, urllib.error, time
    def call(fn,*a,**k):
        for _ in range(8):
            try: return fn(*a,**k)
            except urllib.error.HTTPError as e:
                if e.code==429:
                    w=int(e.headers.get("Retry-After","30") or 30); time.sleep(w+1); continue
                raise
        raise RuntimeError("retries")
    os.makedirs(os.path.join(HERE,"cache"), exist_ok=True)
    for name,(cat,rid,dt_) in FETCH.items():
        rows=[]; page=1; fields=None
        while True:
            r=call(st.run_report,cat,rid,[{"name":"DateType","value":dt_},
                {"name":"From","value":frm},{"name":"To","value":to}],page=page,page_size=5000)
            fields=[f["name"] for f in r.get("fields",[])]; rows+=r.get("data",[])
            if not r.get("hasMore") or not r.get("data"): break
            page+=1; time.sleep(1)
        # Atomic write (tmp + replace): a run killed mid-write can never leave a
        # corrupt cache file behind. Compact separators keep the files ~20% smaller.
        path = os.path.join(HERE, "cache", name + ".json")
        with open(path + ".tmp", "w") as f:
            json.dump({"fields": fields, "rows": rows, "dateType": dt_}, f, separators=(",", ":"))
        os.replace(path + ".tmp", path)
        time.sleep(2)

def build_into(template_path, today=None):
    import auto_update_dashboard as A                         # lazy: avoids import cycle
    today = today or dt.date.today()
    U.load_rows = load_rows                                   # monkeypatch: API rows, not Excel
    html = open(template_path, encoding="utf-8").read()
    new, at_a = A.build_html(html, today)
    open(template_path, "w", encoding="utf-8").write(new)
    return at_a

if __name__ == "__main__":
    for canon in CONFIG:
        rows = load_rows(canon)
        print(f"{canon:26} -> {len(rows):5} excel-rows (row1: {str(rows[1])[:60]})")
